### ISSUE TITLE
Failed to load "Trainer Database"

### ISSUE THREAD

**Issue by vexio** [River707/decomp-editor#3]
Was working fine yesterday, but when I tried to open it today I got an error, with this log:
```
2020-08-18 19:40:56.2300|INFO|DecompEditor.Project|Loading "Item Database"
2020-08-18 19:40:56.2441|INFO|DecompEditor.Project|Deserializing data within "F:\DOCUMENTS\POKEMON DISASSEMBLY\POKEEMERALD\SRC\DATA\ITEMS.H"
2020-08-18 19:40:56.2696|INFO|DecompEditor.Project|Loading "Move Database"
2020-08-18 19:40:56.2754|INFO|DecompEditor.Project|Deserializing data within "F:\DOCUMENTS\POKEMON DISASSEMBLY\POKEEMERALD\SRC\DATA\TEXT\MOVE_NAMES.H"
2020-08-18 19:40:56.2754|INFO|DecompEditor.Project|Loading "Pokemon Species Database"
2020-08-18 19:40:56.2754|INFO|DecompEditor.Project|Deserializing data within "F:\DOCUMENTS\POKEMON DISASSEMBLY\POKEEMERALD\SRC\DATA\TEXT\SPECIES_NAMES.H"
2020-08-18 19:40:56.2936|INFO|DecompEditor.Project|Loading "Trainer Class Database"
2020-08-18 19:40:56.2936|INFO|DecompEditor.Project|Deserializing data within "F:\DOCUMENTS\POKEMON DISASSEMBLY\POKEEMERALD\SRC\DATA\TEXT\TRAINER_CLASS_NAMES.H"
2020-08-18 19:40:56.3053|INFO|DecompEditor.Project|Deserializing data within "F:\DOCUMENTS\POKEMON DISASSEMBLY\POKEEMERALD\SRC\BATTLE_MAIN.C"
2020-08-18 19:40:56.3053|INFO|DecompEditor.Project|Loading "Encounter Music Database"
2020-08-18 19:40:56.3220|INFO|DecompEditor.Project|Deserializing data within "F:\DOCUMENTS\POKEMON DISASSEMBLY\POKEEMERALD\INCLUDE\CONSTANTS\TRAINERS.H"
2020-08-18 19:40:56.3220|INFO|DecompEditor.Project|Loading "Trainer Front Pic Database"
2020-08-18 19:40:56.3220|INFO|DecompEditor.Project|Deserializing data within "F:\DOCUMENTS\POKEMON DISASSEMBLY\POKEEMERALD\SRC\DATA\GRAPHICS\TRAINERS.H"
2020-08-18 19:40:56.3389|INFO|DecompEditor.Project|Deserializing data within "F:\DOCUMENTS\POKEMON DISASSEMBLY\POKEEMERALD\SRC\DATA\TRAINER_GRAPHICS\FRONT_PIC_TABLES.H"
2020-08-18 19:40:56.3389|INFO|DecompEditor.Project|Loading "Trainer Database"
2020-08-18 19:40:56.3389|INFO|DecompEditor.Project|Deserializing data within "F:\DOCUMENTS\POKEMON DISASSEMBLY\POKEEMERALD\SRC\DATA\TRAINER_PARTIES.H"
2020-08-18 19:40:56.3736|INFO|DecompEditor.Project|Deserializing data within "F:\DOCUMENTS\POKEMON DISASSEMBLY\POKEEMERALD\SRC\DATA\TRAINERS.H"
2020-08-18 19:40:56.7788|ERROR|DecompEditor.Project|Failed to load "Trainer Database" from the project directory
System.Collections.Generic.KeyNotFoundException: The given key 'AI_SCRIPT_CHECK_BAD_MOVE' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Truncon.Collections.OrderedDictionary`2.get_Item(TKey key)
   at DecompEditor.TrainerDatabase.Deserializer.TrainerDeserializer.<>c__DisplayClass0_0.<.ctor>b__6(String[] flags)
   at DecompEditor.ParserUtils.StructBodyDeserializer.<>c__DisplayClass16_0.<addEnumMask>b__0(Object obj)
   at DecompEditor.ParserUtils.StructBodyDeserializer.Element.deserializeValue(String line, ValueKind valueKind, ElementValueHandler handler)
   at DecompEditor.ParserUtils.StructBodyDeserializer.deserializeBody(String line, StreamReader stream)
   at DecompEditor.ParserUtils.StructDeserializer`1.tryDeserialize(String currentLine, StreamReader reader)
   at DecompEditor.ParserUtils.ArrayDeserializer.tryDeserialize(String currentLine, StreamReader reader)
   at DecompEditor.ParserUtils.FileDeserializer.deserialize(StreamReader reader)
   at DecompEditor.ProjectDeserializer.deserializeFile(FileDeserializer deserializer, String[] paths)
   at DecompEditor.ProjectDeserializer.deserializeFile(DeserializerBase deserializer, String[] paths)
   at DecompEditor.TrainerDatabase.Deserializer.loadTrainers(ProjectDeserializer deserializer, TrainerDatabase database, Dictionary`2 cppToParty)
   at DecompEditor.TrainerDatabase.Deserializer.deserialize(ProjectDeserializer deserializer, TrainerDatabase database)
   at DecompEditor.TrainerDatabase.deserialize(ProjectDeserializer deserializer)
   at DecompEditor.DatabaseBase.load(ProjectDeserializer deserializer)
   at DecompEditor.Project.load(String projectDir)
```

What's interesting, is that I didn't even touch the trainer's section. I only used the Overworld sprite section. I don't know what I could've done to cause this error. The only thing I can think of that might have caused this issue is the implementation of the Inja and JSON templates for event objects, but that still doesn't quite make sense since it doesn't seem to interact with the Trainers.

**Comment by River707** [comment]
Seems weird. The failure seems to hint that something went wrong when parsing the battle AI defines. Was it able to successfully parse the `Battle AI Database`? Also, have you modified `constants/battle_ai.h` at all or is it still the same as master?

**Comment by vexio** [comment]
I was able to build my Pokeemerald completely fine after getting this error, and I haven't touched `battle_ai.h`

**Comment by OtakuD** [comment]
Also have this error, did not modify the files

**Comment by River707** [comment]
The public facing side of this repo is effectively abandoned. Making tools for vanilla poke-emerald is generally a waste of time IMO (there are so many bad things about the vanilla codebase), that I only do stuff specific to my own personal project now. I've left master untouched effectively to let people who are interested see some starting point, but I don't maintain it anymore.
